import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  DynamicContextProvider,
  EthereumWalletConnectors,
  AlgorandWalletConnectors,
  SolanaWalletConnectors,
  FlowWalletConnectors,
  StarknetWalletConnectors,
  CosmosWalletConnectors
} from "../lib/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <DynamicContextProvider
        settings={{
          environmentId: "4e598b41-f388-489b-a0b3-d24064b1d1ed",
          evmNetworks: [{
            blockExplorerUrls: ['https://etherscan.io/'],
            chainId: 369,
            name: 'Pulse',
            iconUrls: ['https://app.dynamic.xyz/assets/networks/eth.svg'],
            nativeCurrency: { decimals: 18, name: 'Pulse', symbol: 'PLS' },
            networkId: 369,
            privateCustomerRpcUrls: [
              'https://mainnet.infura.io/v3/your-api-key',
            ],
            rpcUrls: ['https://cloudflare-eth.com'],
            vanityName: 'Ethereum'
        }],
        walletConnectors: [
          EthereumWalletConnectors,
          AlgorandWalletConnectors,
          SolanaWalletConnectors,
          FlowWalletConnectors,
          StarknetWalletConnectors,
          CosmosWalletConnectors
        ]
        }}
      >
        <body className={inter.className}>{children}</body>
      </DynamicContextProvider>
    </html>
  );
}
